package com.formula.calculator;

/**
 * 函数名枚举类
 * 统一管理所有支持的函数名称
 */
public enum FunctionName {
    // 常用函数
    SUM("SUM"),
    AVERAGE("AVERAGE"),
    MAX("MAX"),
    MIN("MIN"),
    COUNT("COUNT"),
    COUNTIF("COUNTIF"),
    SUMIF("SUMIF"),
    CONCATENATE("CONCATENATE"),
    DATE("DATE"),
    IF("IF"),
    IFS("IFS"),
    ROUND("ROUND"),
    ROUNDUP("ROUNDUP"),
    ROUNDDOWN("ROUNDDOWN"),
    TESTABC("TESTABC"),
    
    // 逻辑函数
    AND("AND"),
    OR("OR"),
    NOT("NOT"),
    XOR("XOR"),
    SWITCH("SWITCH"),
    IFERROR("IFERROR"),
    IFNA("IFNA"),
    
    // 统计函数
    STDEV("STDEV"),
    STDEVP("STDEVP"),
    VAR("VAR"),
    VARP("VARP"),
    MEDIAN("MEDIAN"),
    MODE("MODE"),
    AVEDEV("AVEDEV"),
    
    // 数学函数 - 基础
    PI("PI"),
    ABS("ABS"),
    SQRT("SQRT"),
    SQRTPI("SQRTPI"),
    SUMSQ("SUMSQ"),
    PRODUCT("PRODUCT"),
    QUOTIENT("QUOTIENT"),
    POWER("POWER"),
    LOG("LOG"),
    LN("LN"),
    EXP("EXP"),
    LOG10("LOG10"),
    LOG2("LOG2"),
    
    // 数学函数 - 取整
    CEILING("CEILING"),
    CEILING_MATH("CEILING.MATH"),
    FLOOR("FLOOR"),
    FLOOR_MATH("FLOOR.MATH"),
    MROUND("MROUND"),
    INT("INT"),
    TRUNC("TRUNC"),
    SIGN("SIGN"),
    EVEN("EVEN"),
    ODD("ODD"),
    
    // 数学函数 - 数论
    GCD("GCD"),
    LCM("LCM"),
    FACT("FACT"),
    FACTDOUBLE("FACTDOUBLE"),
    COMBIN("COMBIN"),
    PERMUT("PERMUT"),
    MOD("MOD"),
    ISEVEN("ISEVEN"),
    ISODD("ISODD"),
    
    // 数学函数 - 随机
    RAND("RAND"),
    RANDBETWEEN("RANDBETWEEN"),
    
    // 数学函数 - 排序
    LARGE("LARGE"),
    SMALL("SMALL"),
    
    // 数学函数 - 平均数
    GEOMEAN("GEOMEAN"),
    HARMEAN("HARMEAN"),
    
    // 数学函数 - 角度转换
    DEGREES("DEGREES"),
    RADIANS("RADIANS"),
    
    // 数学函数 - 三角函数
    SIN("SIN"),
    COS("COS"),
    TAN("TAN"),
    ASIN("ASIN"),
    ACOS("ACOS"),
    ATAN("ATAN"),
    ATAN2("ATAN2"),
    
    // 数学函数 - 双曲函数
    SINH("SINH"),
    COSH("COSH"),
    TANH("TANH"),
    ASINH("ASINH"),
    ACOSH("ACOSH"),
    ATANH("ATANH"),
    
    // 数学函数 - 扩展
    ACOT("ACOT"),
    ACOTH("ACOTH"),
    AGGREGATE("AGGREGATE"),
    ARABIC("ARABIC"),
    BASE("BASE"),
    CEILING_PRECISE("CEILING.PRECISE"),
    FLOOR_PRECISE("FLOOR.PRECISE"),
    ISO_CEILING("ISO.CEILING"),
    MUNIT("MUNIT"),
    MULTINOMIAL("MULTINOMIAL"),
    ROMAN("ROMAN"),
    SEC("SEC"),
    SECH("SECH"),
    CSC("CSC"),
    CSCH("CSCH"),
    COT("COT"),
    COTH("COTH"),
    
    // 文本函数
    TEXT("TEXT"),
    UPPER("UPPER"),
    LOWER("LOWER"),
    PROPER("PROPER"),
    LEN("LEN"),
    LEFT("LEFT"),
    RIGHT("RIGHT"),
    MID("MID"),
    FIND("FIND"),
    SEARCH("SEARCH"),
    REPLACE("REPLACE"),
    SUBSTITUTE("SUBSTITUTE"),
    TRIM("TRIM"),
    CONCAT("CONCAT"),
    TEXTJOIN("TEXTJOIN"),
    VALUE("VALUE"),
    CHAR("CHAR"),
    CODE("CODE"),
    REPT("REPT"),
    EXACT("EXACT"),
    CLEAN("CLEAN"),
    T("T"),
    FIXED("FIXED"),
    DOLLAR("DOLLAR"),
    NUMBERVALUE("NUMBERVALUE"),
    
    // 日期时间函数
    TODAY("TODAY"),
    NOW("NOW"),
    YEAR("YEAR"),
    MONTH("MONTH"),
    DAY("DAY"),
    HOUR("HOUR"),
    MINUTE("MINUTE"),
    SECOND("SECOND"),
    WEEKDAY("WEEKDAY"),
    WEEKNUM("WEEKNUM"),
    DAYS("DAYS"),
    DAYS360("DAYS360"),
    EDATE("EDATE"),
    EOMONTH("EOMONTH"),
    YEARFRAC("YEARFRAC"),
    TIME("TIME"),
    TIMEVALUE("TIMEVALUE"),
    DATEVALUE("DATEVALUE"),
    WORKDAY("WORKDAY"),
    WORKDAY_INTL("WORKDAY.INTL"),
    NETWORKDAYS("NETWORKDAYS"),
    NETWORKDAYS_INTL("NETWORKDAYS.INTL"),
    DATEDIF("DATEDIF"),
    
    // 查找和引用函数
    VLOOKUP("VLOOKUP"),
    HLOOKUP("HLOOKUP"),
    INDEX("INDEX"),
    MATCH("MATCH"),
    INDIRECT("INDIRECT"),
    OFFSET("OFFSET"),
    ROW("ROW"),
    COLUMN("COLUMN"),
    ROWS("ROWS"),
    COLUMNS("COLUMNS"),
    CHOOSE("CHOOSE"),
    ADDRESS("ADDRESS"),
    AREAS("AREAS"),
    TRANSPOSE("TRANSPOSE"),
    UNIQUE("UNIQUE"),
    SORT("SORT"),
    FILTER("FILTER"),
    XLOOKUP("XLOOKUP"),
    XMATCH("XMATCH"),
    
    // 信息函数
    ISBLANK("ISBLANK"),
    ISNUMBER("ISNUMBER"),
    ISTEXT("ISTEXT"),
    ISLOGICAL("ISLOGICAL"),
    ISERROR("ISERROR"),
    ISNA("ISNA"),
    ISERR("ISERR"),
    ISFORMULA("ISFORMULA"),
    ISREF("ISREF"),
    N("N"),
    TYPE("TYPE"),
    CELL("CELL"),
    INFO("INFO"),
    ERROR_TYPE("ERROR.TYPE"),
    NA("NA"),
    TRUE("TRUE"),
    FALSE("FALSE"),
    
    // 统计函数 - 扩展
    AVERAGEA("AVERAGEA"),
    AVERAGEIF("AVERAGEIF"),
    AVERAGEIFS("AVERAGEIFS"),
    COUNTBLANK("COUNTBLANK"),
    COUNTA("COUNTA"),
    COUNTIFS("COUNTIFS"),
    SUMIFS("SUMIFS"),
    FREQUENCY("FREQUENCY"),
    PERCENTILE("PERCENTILE"),
    PERCENTILE_INC("PERCENTILE.INC"),
    PERCENTILE_EXC("PERCENTILE.EXC"),
    QUARTILE("QUARTILE"),
    QUARTILE_INC("QUARTILE.INC"),
    QUARTILE_EXC("QUARTILE.EXC"),
    RANK("RANK"),
    RANK_AVG("RANK.AVG"),
    RANK_EQ("RANK.EQ"),
    PERCENTRANK("PERCENTRANK"),
    PERCENTRANK_INC("PERCENTRANK.INC"),
    PERCENTRANK_EXC("PERCENTRANK.EXC"),
    CORREL("CORREL"),
    COVAR("COVAR"),
    COVARIANCE_P("COVARIANCE.P"),
    COVARIANCE_S("COVARIANCE.S"),
    DEVSQ("DEVSQ"),
    FORECAST("FORECAST"),
    FORECAST_LINEAR("FORECAST.LINEAR"),
    GROWTH("GROWTH"),
    INTERCEPT("INTERCEPT"),
    SLOPE("SLOPE"),
    LINEST("LINEST"),
    LOGEST("LOGEST"),
    TREND("TREND"),
    STEYX("STEYX"),
    RSQ("RSQ"),
    PEARSON("PEARSON"),
    SKEW("SKEW"),
    SKEW_P("SKEW.P"),
    KURT("KURT"),
    MAXA("MAXA"),
    MINA("MINA"),
    TRIMMEAN("TRIMMEAN"),
    Z_TEST("Z.TEST"),
    T_TEST("T.TEST"),
    F_TEST("F.TEST"),
    CHISQ_TEST("CHISQ.TEST"),
    CONFIDENCE("CONFIDENCE"),
    CONFIDENCE_NORM("CONFIDENCE.NORM"),
    CONFIDENCE_T("CONFIDENCE.T"),
    
    // 统计函数 - 分布函数
    NORM_DIST("NORM.DIST"),
    NORM_INV("NORM.INV"),
    NORM_S_DIST("NORM.S.DIST"),
    NORM_S_INV("NORM.S.INV"),
    BINOM_DIST("BINOM.DIST"),
    BINOM_INV("BINOM.INV"),
    POISSON_DIST("POISSON.DIST"),
    EXPON_DIST("EXPON.DIST"),
    GAMMA_DIST("GAMMA.DIST"),
    GAMMA_INV("GAMMA.INV"),
    BETA_DIST("BETA.DIST"),
    BETA_INV("BETA.INV"),
    WEIBULL_DIST("WEIBULL.DIST"),
    LOGNORM_DIST("LOGNORM.DIST"),
    LOGNORM_INV("LOGNORM.INV"),
    HYPGEOM_DIST("HYPGEOM.DIST"),
    NEGBINOM_DIST("NEGBINOM.DIST"),
    F_DIST("F.DIST"),
    F_INV("F.INV"),
    T_DIST("T.DIST"),
    T_INV("T.INV"),
    CHISQ_DIST("CHISQ.DIST"),
    CHISQ_INV("CHISQ.INV"),
    
    // 财务函数
    PMT("PMT"),
    IPMT("IPMT"),
    PPMT("PPMT"),
    FV("FV"),
    PV("PV"),
    NPV("NPV"),
    IRR("IRR"),
    MIRR("MIRR"),
    RATE("RATE"),
    NPER("NPER"),
    CUMIPMT("CUMIPMT"),
    CUMPRINC("CUMPRINC"),
    DB("DB"),
    DDB("DDB"),
    SLN("SLN"),
    SYD("SYD"),
    VDB("VDB"),
    ACCRINT("ACCRINT"),
    ACCRINTM("ACCRINTM"),
    COUPDAYBS("COUPDAYBS"),
    COUPDAYS("COUPDAYS"),
    COUPDAYSNC("COUPDAYSNC"),
    COUPNCD("COUPNCD"),
    COUPNUM("COUPNUM"),
    COUPPCD("COUPPCD"),
    DISC("DISC"),
    DURATION("DURATION"),
    EFFECT("EFFECT"),
    INTRATE("INTRATE"),
    MDURATION("MDURATION"),
    NOMINAL("NOMINAL"),
    PRICE("PRICE"),
    PRICEDISC("PRICEDISC"),
    PRICEMAT("PRICEMAT"),
    RECEIVED("RECEIVED"),
    TBILLEQ("TBILLEQ"),
    TBILLPRICE("TBILLPRICE"),
    TBILLYIELD("TBILLYIELD"),
    YIELD("YIELD"),
    YIELDDISC("YIELDDISC"),
    YIELDMAT("YIELDMAT"),
    XIRR("XIRR"),
    XNPV("XNPV"),
    
    // 工程函数
    BESSELI("BESSELI"),
    BESSELJ("BESSELJ"),
    BESSELK("BESSELK"),
    BESSELY("BESSELY"),
    BIN2DEC("BIN2DEC"),
    BIN2HEX("BIN2HEX"),
    BIN2OCT("BIN2OCT"),
    DEC2BIN("DEC2BIN"),
    DEC2HEX("DEC2HEX"),
    DEC2OCT("DEC2OCT"),
    HEX2BIN("HEX2BIN"),
    HEX2DEC("HEX2DEC"),
    HEX2OCT("HEX2OCT"),
    OCT2BIN("OCT2BIN"),
    OCT2DEC("OCT2DEC"),
    OCT2HEX("OCT2HEX"),
    COMPLEX("COMPLEX"),
    IMABS("IMABS"),
    IMAGINARY("IMAGINARY"),
    IMARGUMENT("IMARGUMENT"),
    IMCONJUGATE("IMCONJUGATE"),
    IMCOS("IMCOS"),
    IMCOSH("IMCOSH"),
    IMCOT("IMCOT"),
    IMCSC("IMCSC"),
    IMCSCH("IMCSCH"),
    IMDIV("IMDIV"),
    IMEXP("IMEXP"),
    IMLN("IMLN"),
    IMLOG10("IMLOG10"),
    IMLOG2("IMLOG2"),
    IMPOWER("IMPOWER"),
    IMPRODUCT("IMPRODUCT"),
    IMREAL("IMREAL"),
    IMSEC("IMSEC"),
    IMSECH("IMSECH"),
    IMSIN("IMSIN"),
    IMSINH("IMSINH"),
    IMSQRT("IMSQRT"),
    IMSUB("IMSUB"),
    IMSUM("IMSUM"),
    IMTAN("IMTAN"),
    DELTA("DELTA"),
    GESTEP("GESTEP"),
    ERF("ERF"),
    ERF_PRECISE("ERF.PRECISE"),
    ERFC("ERFC"),
    ERFC_PRECISE("ERFC.PRECISE"),
    
    // 兼容性函数
    BETADIST("BETADIST"),
    BETAINV("BETAINV"),
    BINOMDIST("BINOMDIST"),
    CHIDIST("CHIDIST"),
    CHIINV("CHIINV"),
    CHITEST("CHITEST"),
    CRITBINOM("CRITBINOM"),
    EXPONDIST("EXPONDIST"),
    FDIST("FDIST"),
    FINV("FINV"),
    FTEST("FTEST"),
    GAMMADIST("GAMMADIST"),
    GAMMAINV("GAMMAINV"),
    HYPGEOMDIST("HYPGEOMDIST"),
    LOGINV("LOGINV"),
    LOGNORMDIST("LOGNORMDIST"),
    NEGBINOMDIST("NEGBINOMDIST"),
    NORMDIST("NORMDIST"),
    NORMINV("NORMINV"),
    NORMSDIST("NORMSDIST"),
    NORMSINV("NORMSINV"),
    POISSON("POISSON"),
    TDIST("TDIST"),
    TINV("TINV"),
    TTEST("TTEST"),
    VAR_S("VAR.S"),
    VAR_P("VAR.P"),
    VARA("VARA"),
    VARPA("VARPA"),
    WEIBULL("WEIBULL"),
    ZTEST("ZTEST");
    
    private final String name;
    
    FunctionName(String name) {
        this.name = name;
    }
    
    /**
     * 获取函数名称
     */
    public String getName() {
        return name;
    }
    
    /**
     * 根据名称查找枚举
     */
    public static FunctionName fromName(String name) {
        if (name == null) {
            return null;
        }
        // 处理点号分隔的函数名（如CEILING.MATH）
        String normalizedName = name.replace(".", "_");
        for (FunctionName fn : values()) {
            if (fn.name.equals(name) || fn.name().equals(normalizedName)) {
                return fn;
            }
        }
        return null;
    }
    
    @Override
    public String toString() {
        return name;
    }
}

